### ISSUE TITLE
Error getting config

### ISSUE THREAD

**Issue by Luuc15** [marionnewlevant/craft3-snitch#1]
Hi,

When installing this plugin on the most recent version of the craft 3 cms (3.0.0-28), nothing happens.
What i saw that happend was that the javascript got a faulty json response, with an error that config service could not be found.

Below you will find an image with the error and url that was called:

![schermafbeelding 2017-09-28 om 15 26 14](https://user-images.githubusercontent.com/661751/30969107-b482bbf0-a461-11e7-9fbb-2965f8f8af09.png)

**Comment by marionnewlevant** [comment]
I am going to update this to the latest Craft3, and also put it in the craft-snitch repo. v1 will be the craft2 version, v2 will be the craft3 version. I think some things have changed in the way craft3 handles config files.
